
INSERT INTO `electratech-bugtracker`.bug(project_name, issue_type, description,trouble_shooting,is_resolved, resolution,recorded_date, update_date) 
VALUES
('Ecommerce', 'Setup Error','Entity Unknown property', 'Entity import resolving to Javax instead of Jakarta. Jakarta not present in build path, research at GeekForGeeks.com & stackoverflow.com', True, 'update pom.xml to change Spring Boot version from 2.x.x to 3.1.1','2023-07-20 08:00:00', '2023-07-20 08:00:00'),
('Ecommerce','API','Undefined object "order" in angular ts file when viewed in browser console','Test in postman, status =ok. Order history not displaying in browser',true,'corrected typo in service. update _embeded to _embedded','2023-08-18 08:00:00','2023-08-19 08:00:00'),
('Ecommerce','Angular','Total price not displaying in orders history table','total price missing from DB when submitting purchase from form. Constructor missing in Order.ts',true,'update entity Orders.ts to include parametorized constructor and update checkout.component.ts to totalPrice = this.totalPrice;','2023-08-19 08:00:00','2023-08-20 08:00:00'),
('Ecommerce','Okta','Error 403 after adding Okta','Orders listed in DB but not displaying. Checked for typos',true,'found typo in URL; corrected from http:/localhost:8080/api/orders to http://localhost:8080/api/orders','2023-08-21 08:00:00','2023-08-21 08:00:00'),
('Ecommerce','Angular','Purchase Button not reseting form','Searched for Typos',false,'','2023-08-24 08:00:00','2023-08-24 08:00:00'),
('Ecommerce','Spring Boot','Keytool is not recognized','copy and pasted command. Tried from powershell, cmd, and gitbash. Reseached in Q&A section below tutorial. Researched on Stack Overflow. Readded the class path. Researched Keytool utility at various tuturial websites. Bealdung, geekforgeeks, oracle, w3c etc.. Found tutorial at : https://codewithandrea.com/articles/keytool-command-not-found-how-to-fix-windows-macos/ ',true,'Did a keyword search for keytool to find exe. Discovered that my jre java  17 is not installed in programs folder. Updated classpath to correct folder. ','2023-08-24 08:00:00','2023-08-24 08:00:00'),
('Ecommerce','Spring Boot','Class not found exception','Attempted to reboot the server.  Looked for typos in the application.properties file. Researched the java classpath. Rewatched the tutorial video. Copy and pasted application.properties file from tutorial resource file. Reseached keystore,closed project, reopened and performed a Maven update ',true,'issue cleared','2023-08-30 08:00:00','2023-08-30 08:00:00'),
('Beck & Butler website','API','CORS error in browser console','/send email not working from fE but confirmed working in postman, Verified @Crossorigin annotation and URL correct in rest controller. Added @Crossorigin at controller level. Configured RestConfiguration file with CORS policy. created new CORS config class with cors policy "/**", URL incorrect in FE',true,'updated URL in front end from /sendEmail to /sendMail','2023-09-13 08:00:00','2023-09-15 08:00:00'),
('Beck & Butler website','Angular','Null value returned in contactForm.message','added" message: new FormControl('') })" to validation group. Checked spelling',true,'corrected formControlName="message " to formControlName="message". Removed space ','2023-09-16 08:00:00','2023-09-16 08:00:00');